name: Publish to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3.0.0-beta.4

      - name: Set up Environment Variables
        run: |
          echo "GPR_USER=${{ secrets.GPR_USER }}" >> $GITHUB_ENV
          echo "GPR_TOKEN=${{ secrets.GPR_TOKEN }}" >> $GITHUB_ENV
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> $GITHUB_ENV

      - name: Build and Publish
        run: |
          chmod +x gradlew
          ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}